// <auto-generated />
namespace UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class No_Email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(No_Email));
        
        string IMigrationMetadata.Id
        {
            get { return "202103241352181_No_Email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
